### ISSUE TITLE
Couldn't find "libkhadas_npu_jni.so" //  Cannot run program "su": error=13, Permission denied

### ISSUE THREAD

**Issue by AlperenEnesBayar** [khadas/khadas_android_npu_app#3]
I am getting this error when trying to open any model. What am I doing wrong?
Thanks in advance for any help.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.khadas.npudemo, PID: 4835
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.khadas.npudemo-rZ7IdzA5Z5jfqoFwjWD0kw==/base.apk"],nativeLibraryDirectories=[/data/app/com.khadas.npudemo-rZ7IdzA5Z5jfqoFwjWD0kw==/lib/x86, /system/lib]]] couldn't find "libkhadas_npu_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.khadas.npudemo.KhadasNpuManager.<clinit>(KhadasNpuManager.java:14)
        at com.khadas.npudemo.CameraActivity.<init>(CameraActivity.java:141)
        at com.khadas.npudemo.ClassifierActivity.<init>(ClassifierActivity.java:11)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 4835 SIG: 9
`

**Comment by AlperenEnesBayar** [comment]
I solved this problem by doing this 

inside build.gradle (:app) 
```
android {
    defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
```

But now 
`java.io.IOException: Cannot run program "su": error=13, Permission denied`
it gives this error
